// Generated by dia2code
#ifndef __ENGINE__H
#define __ENGINE__H

#include "engine/CommandTypeId.h"
#include "engine/Command.h"
#include "engine/Engine.h"
#include "engine/MoveCommand.h"
#include "engine/AttackCommand.h"
#include "engine/Action.h"
#include "engine/HealCommand.h"
#endif
